-- Row Counts
SELECT COUNT(*) FROM SNOWFLAKE_CUSTOMERS;
SELECT COUNT(*) FROM SNOWFLAKE_ORDERS;
SELECT COUNT(*) FROM SNOWFLAKE_FEEDBACK;

-- Username Field Check
SELECT email, username FROM SNOWFLAKE_CUSTOMERS LIMIT 5;

-- Event Table Validation
SELECT * FROM ORDER_EVENTS LIMIT 10;
SELECT DISTINCT event_type FROM ORDER_EVENTS;
